services:
  - type: web
    name: stockwise-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
